import { Inter } from "next/font/google";
import   Navbar   from "./component/navbar";
import Footer from "./component/footer";
import axios from 'axios';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchData(backend_url) {
  try {
    const response = await axios.get(`${backend_url}/auth`);
    const data = response.data;
    return data; // Return the fetched data
  } catch (error) {
    console.error('Error fetching data:', error);
    // Handle errors appropriately (e.g., display an error message)
  }
}
export default async function RootLayout({ children }) {

  const backendUrl = process.env.BACKEND_URL;
  const response = await fetchData(backendUrl)

  let status = response['message']


  return (
    <html className="static" lang="en">
      <body className="flex flex-col h-svh">
            <Navbar loginStatus={status}/>
            <div className="mt-20">
              {children}
            </div>
            <Footer/>
      </body>
    </html>
  );
}
