import { Inter } from "next/font/google";
import   Navbar   from "./component/navbar";
import Footer from "./component/footer";
import axios from 'axios';
// import  CheckAuth  from "./component/checkauth";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {

return (
  <html className="static" lang="en">
      <body className="flex flex-col h-svh">
            <Navbar/>
            <div className="mt-20">
              {children}
            </div>
            <Footer/>
      </body>
    </html>
  );
}
